//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_drumGame : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean CenterCamera
        {
            get
            {
                return SteamVR_Actions.drumGame_CenterCamera;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.drumGame_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.drumGame_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back
        {
            get
            {
                return SteamVR_Actions.drumGame_Back;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuUp
        {
            get
            {
                return SteamVR_Actions.drumGame_MenuUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuDown
        {
            get
            {
                return SteamVR_Actions.drumGame_MenuDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuLeft
        {
            get
            {
                return SteamVR_Actions.drumGame_MenuLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuRight
        {
            get
            {
                return SteamVR_Actions.drumGame_MenuRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.drumGame_Haptic;
            }
        }
    }
}
